import { createManifestHandler } from "@/lib/routes/manifest";
import packageJson from "../../../../package.json";

export const GET = createManifestHandler({
  id: "ye-wiki",
  name: "Wiki",
  version: packageJson.version,
  description: "Privacy-friendly Wikipedia reader with 300+ languages",
  icon: "BookOpen",
  accent_color: "#3b82f6",
  permissions: ["notifications:send", "timeline:write"],
  surfaceSchemaVersion: 1,
  surfaces: [
    {
      id: "default-notification",
      kind: "notification",
      placement: "notification-center",
      name: "Wiki notification",
      description: "Rich Wiki notification body",
      embedPath: "/embed/notification/default",
      permissions: ["notifications:send"],
    },
    {
      id: "app-settings",
      kind: "settings-panel",
      placement: "app-settings",
      name: "App Settings",
      description: "App-owned settings panel",
      embedPath: "/embed/settings",
      permissions: [],
    },
    {
      id: "featured-article",
      kind: "widget",
      placement: "dashboard",
      name: "Featured Article",
      description: "Today's featured Wikipedia article",
      embedPath: "/embed/widget/featured-article",
      permissions: [],
      defaultSize: { width: 25, height: 28 },
      minSize: { width: 18, height: 20 },
      maxSize: { width: 45, height: 50 },
      refreshInterval: 86400,
    },
    {
      id: "today-in-history",
      kind: "widget",
      placement: "dashboard",
      name: "Today in History",
      description: "Historical events that happened on this day",
      embedPath: "/embed/widget/today-in-history",
      permissions: [],
      defaultSize: { width: 25, height: 28 },
      minSize: { width: 18, height: 20 },
      maxSize: { width: 45, height: 50 },
      refreshInterval: 86400,
    },
    {
      id: "article-summary",
      kind: "info-card",
      placement: "timeline",
      name: "Article summary",
      description: "Wikipedia article summary card",
      embedPath: "/embed/card/article",
      permissions: [],
      triggers: ["wikipedia.org"],
    },
    {
      id: "wiki-article-read",
      kind: "timeline-card",
      placement: "timeline",
      name: "Article read",
      description: "Wikipedia article read",
      embedPath: "/embed/timeline/article",
      permissions: ["timeline:write"],
      triggers: ["wiki-article-read"],
    },
    {
      id: "wiki-article-edit",
      kind: "timeline-card",
      placement: "timeline",
      name: "Article edited",
      description: "Wikipedia article edited",
      embedPath: "/embed/timeline/article",
      permissions: ["timeline:write"],
      triggers: ["wiki-article-edit"],
    },
  ],
  inter_app: {
    provides: [
      { type: "info-card", description: "Article summary info cards" },
      { type: "search", description: "Wikipedia search results" },
    ],
  },
  internet: {
    proxy: [
      { host: "*.wikipedia.org", paths: ["/api/rest_v1/*", "/w/api.php*"], methods: ["GET"], scope: "user" },
      { host: "upload.wikimedia.org", paths: ["/*"], methods: ["GET"], scope: "user" },
    ],
  },
  settings: {
    schema: [
      {
        key: "language",
        type: "select",
        label: "Wikipedia Language",
        default: "en",
        options: [
          { label: "English", value: "en" },
          { label: "Deutsch", value: "de" },
          { label: "Français", value: "fr" },
          { label: "Español", value: "es" },
          { label: "Русский", value: "ru" },
        ],
      },
    ],
  },
});
